#pragma once

#include "NativeGameplayTags.h"

namespace TPSGameplayTags
{
	TPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	TPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	TPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	TPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);


	TPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Fire);
	TPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Grenade);
	TPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Aim);
	
	TPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Actor_Character);
	TPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Actor_Character_Player);
	TPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Actor_Character_AI);

	

	
}
